# Generated by Django 5.1.3 on 2024-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False,
                        help_text="고유 아이디",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "social_id",
                    models.CharField(help_text="유저 플랫폼 고유 아이디", max_length=100, unique=True),
                ),
                (
                    "username",
                    models.CharField(help_text="플랫폼 유저 이름", max_length=50, unique=True),
                ),
                ("age_range", models.CharField(help_text="유저 연령대", max_length=50)),
                ("birthday", models.CharField(help_text="생일 일자", max_length=50)),
                (
                    "email",
                    models.CharField(help_text="유저 플랫폼 가입 이메일", max_length=50),
                ),
                ("platform", models.CharField(help_text="플랫폼 명칭", max_length=50)),
                (
                    "profile_image",
                    models.CharField(help_text="프로필 이미지 사진 URL", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="유저 활성화 여부"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, help_text="마지막 로그인 일자"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="최초 가입 일자"),
                ),
            ],
            options={
                "db_table": "service_user",
                "constraints": [models.UniqueConstraint(fields=("social_id",), name="unique_social_id")],
            },
        ),
    ]
