[tool.poetry]
name = "cali-api"
version = "0.1.0"
description = "Calendar Playlist"
readme = "README.md"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.12"
black = "24.4.2"
click = ">=8.1.7"
django-cors-headers = ">=4.6.0"
django-environ = ">=0.11.2"
djangorestframework-simplejwt = ">=5.3.1"
djangorestframework = ">=3.15.2"
drf-spectacular = ">=0.27.2"
requests = ">=2.32.3"
ruff = ">=0.8.0"
dj-rest-auth = ">=7.0.0"
pillow = ">=11.0.0"
django-storages = ">=1.14.4"
boto3 = ">=1.35.71"
google-api-python-client = ">=2.154.0"
selenium = ">=4.27.1"
psycopg2-binary = "^2.9.10"
gunicorn = "^23.0.0"

[tool.poetry.dev-dependencies]
django-debug-toolbar = ">=4.4.6"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
indent-width = 4
ignore = ["F405", "F401"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = false
docstring-code-line-length = "dynamic"
