# Generated by Django 5.1.4 on 2024-12-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_calendar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubemusicevent",
            name="music_url",
        ),
        migrations.AlterField(
            model_name="eventcalendar",
            name="comment",
            field=models.CharField(default="", help_text="이미지 표현 될 메시지", max_length=100),
        ),
    ]
