# Generated by Django 5.1.4 on 2024-12-18 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_calendar", "0002_remove_youtubemusicevent_music_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcalendar",
            options={"ordering": ["calendar_dt", "seq_no"]},
        ),
        migrations.AlterField(
            model_name="eventcalendar",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="youtubemusicevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youtube_music",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
