# Generated by Django 5.1.3 on 2024-11-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_photo",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_photo_file",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photo"),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
