# Generated by Django 5.1.4 on 2024-12-12 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("event_calendar", "0002_remove_youtubemusicevent_music_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("writer_name", models.CharField(blank=True, max_length=20, null=True)),
                ("detail", models.TextField(help_text="방명록 내용")),
                (
                    "writer_ip",
                    models.GenericIPAddressField(blank=True, help_text="작성자 IP 주소", null=True),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestbooks",
                        to="event_calendar.eventcalendar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestbooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "guest_book",
                "ordering": ["created_at"],
            },
        ),
    ]
